apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mhserveremu
  namespace: mhserveremu
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: mhserveremu-redirect-https@kubernetescrd,mhserveremu-mh-auth-stripprefix@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - mhserveremu.localdev
      secretName: mhserveremu-tls
  rules:
    - host: mhserveremu.localdev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mhserveremu
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mhserveremu-static
  namespace: mhserveremu
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: mhserveremu-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - static.mhserveremu.localdev
      secretName: mhserveremu-tls
  rules:
    - host: static.mhserveremu.localdev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mhserveremu-static
                port:
                  number: 80
