apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mhserveremu
  namespace: mhserveremu
spec:
  parentRefs:
    - name: mhserveremu
      sectionName: https
  hostnames:
    - mhserveremu.localdev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /AuthServer
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: mhserveremu
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: mhserveremu
          port: 8080

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mhserveremu-static
  namespace: mhserveremu
spec:
  parentRefs:
    - name: mhserveremu
      sectionName: https-static
  hostnames:
    - static.mhserveremu.localdev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: mhserveremu-static
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mhserveremu-redirect-http
  namespace: mhserveremu
spec:
  parentRefs:
    - name: mhserveremu
      sectionName: http
  hostnames:
    - mhserveremu.localdev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            port: 443
            statusCode: 301

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mhserveremu-static-redirect-http
  namespace: mhserveremu
spec:
  parentRefs:
    - name: mhserveremu
      sectionName: http-static
  hostnames:
    - static.mhserveremu.localdev
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            port: 443
            statusCode: 301
