---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mhserveremu-static
  namespace: mhserveremu
  labels:
    app: mhserveremu-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mhserveremu-static
  template:
    metadata:
      labels:
        app: mhserveremu-static
    spec:
      automountServiceAccountToken: false
      containers:
        - name: nginx
          image: nginx:1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: static-files
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: static-files
          configMap:
            name: mhserveremu-static-files
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mhserveremu
  namespace: mhserveremu
  labels:
    app: mhserveremu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mhserveremu
  template:
    metadata:
      labels:
        app: mhserveremu
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mhserveremu
          image: docker.io/zkoesters/mhserveremu:0.7.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          env:
            - name: FRONTEND_BIND_IP
              value: "0.0.0.0"
            - name: AUTH_ADDRESS
              value: "*"
            - name: FRONTEND_PUBLIC_ADDRESS
              value: "fe.mhserveremu.localdev"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: game-tcp
              containerPort: 4306
              protocol: TCP
            - name: game-udp
              containerPort: 4306
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /data
          stdin: true
          tty: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mhserveremu-data
