apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - service.yaml
  - deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: mhserveremu-static-files
    namespace: mhserveremu
    files:
      - SiteConfig.xml=../../../../common/mhserveremu/SiteConfig.xml
      - LiveLoadingTips.xml=../../../../common/mhserveremu/LiveLoadingTips.xml
    options:
      labels:
        app: mhserveremu-static
