apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mhserveremu-tls
  namespace: mhserveremu
spec:
  secretName: mhserveremu-tls
  commonName: mhserveremu.localdev
  dnsNames:
    - mhserveremu.localdev
    - static.mhserveremu.localdev
  issuerRef:
    kind: ClusterIssuer
    name: mhserveremu-selfsigned-cluster-issuer
